### ISSUE TITLE
How to enable employers to register companies theirself from frontend.

### ISSUE THREAD

**Issue by ankushsingh** [Alfraganus/uzautojobs#3]

**Comment by Alfraganus** [comment]
front frondend it was hidden and commented but code has been written to register companies theirselves

**Comment by Alfraganus** [comment]
front frondend it was hidden and commented but code has been written to register companies theirselves, let me know if you found this

**Comment by ankushsingh** [comment]
Yes thank you so much @Alfraganus i got it.

**Comment by Alfraganus** [comment]
> Yes thank you so much @Alfraganus i got it.

anytime :-)
